=== dom111/civ-clone/src/Plugin/Schema.json
{
  "$id": "https://github.com/dom111/civ-clone/plugin.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "pluginName": {
      "type": "string",
      "description": "The name of the plugin. This MUST match the directory that contains the plugin.",
      "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$"
    }
  },

  "title": "Plugin",
  "properties": {
    "name": {
      "$ref": "#/definitions/pluginName"
    },
    "description": {
      "description": "An optional description of the plugin",
      "type": "string"
    },
    "version": {
      "description": "A version definition in MAJOR.MINOR.PATCH.",
      "type": "string",
      "pattern": "^[0-9]+.[0-9]+.[0-9]+(-[A-Za-z0-9]+)*$"
    },
    "components": {
      "description": "A list of the plugin's components.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "description": "The type of component.",
            "enum": [
              "script"
            ]
          },
          "file": {
            "description": "The relative path to the component.",
            "type": "string",
            "pattern": "([A-Za-z0-9]+/)*[A-Za-z0-9]+(.[A-Za-z0-9]+)"
          }
        }
      }
    },
    "dependencies": {
      "description": "The other plugins that this plugin is dependent on.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/pluginName"
      }
    },
    "required": {
      "name": true,
      "version": true
    }
  },
  "type": "object"
}

=== dom111/civ-clone/plugins/enabled/base-city-improvement-courthouse/plugin.json
{
  "name": "base-city-improvement-courthouse",
  "version": "0.1.0",
  "dependencies": [
    "base-city",
    "base-city-improvement-palace",
    "base-city-improvements",
    "base-currency",
    "core-city-improvement",
    "core-rules",
    "core-registry",
    "core-rules-registry"
  ],
  "components": [
    {
      "type": "script",
      "file": "registerAvailableCityBuildItem.js"
    },
    {
      "type": "script",
      "file": "Rules/City/build-cost.js"
    },
    {
      "type": "script",
      "file": "Rules/City/cost.js"
    },
    {
      "type": "script",
      "file": "Rules/City/build.js"
    },
    {
      "type": "script",
      "file": "registerRules.js"
    },
    {
      "type": "script",
      "file": "Courthouse.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-goody-hut-unit/plugin.json
{
  "name": "base-goody-hut-unit",
  "version": "0.1.0",
  "dependencies": [
    "core-goody-huts",
    "core-rules-registry",
    "core-rules",
    "base-unit-horseman",
    "base-unit-swordman",
    "core-unit"
  ],
  "components": [
    {
      "type": "script",
      "file": "Rules/GoodyHut/action.js"
    },
    {
      "type": "script",
      "file": "registerRules.js"
    },
    {
      "type": "script",
      "file": "Unit.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-wonder/plugin.json
{
  "name": "base-wonder",
  "version": "0.1.0",
  "dependencies": [
    "core-rules",
    "core-wonder",
    "base-city",
    "base-city-happiness",
    "base-science",
    "base-terrain-yield-trade",
    "base-unit",
    "core-city-improvement",
    "core-unit",
    "base-city-improvements-civ1"
  ],
  "components": [
    {
      "type": "script",
      "file": "Wonders/Oracle.js"
    },
    {
      "type": "script",
      "file": "Wonders/HangingGardens.js"
    },
    {
      "type": "script",
      "file": "Wonders/GreatWall.js"
    },
    {
      "type": "script",
      "file": "Wonders/Pyramids.js"
    },
    {
      "type": "script",
      "file": "Wonders/GreatLibrary.js"
    },
    {
      "type": "script",
      "file": "Wonders/CopernicusObservatory.js"
    },
    {
      "type": "script",
      "file": "Wonders/Colossus.js"
    },
    {
      "type": "script",
      "file": "Wonders/Lighthouse.js"
    },
    {
      "type": "script",
      "file": "Wonders/MagellansExpedition.js"
    },
    {
      "type": "script",
      "file": "Wonders.js"
    },
    {
      "type": "script",
      "file": "Rules/City/build-cost.js"
    },
    {
      "type": "script",
      "file": "Rules/City/build.js"
    },
    {
      "type": "script",
      "file": "registerWonders.js"
    },
    {
      "type": "script",
      "file": "Rules/City/building-complete.js"
    },
    {
      "type": "script",
      "file": "registerRules.js"
    },
    {
      "type": "script",
      "file": "Rules/Unit/yield.js"
    },
    {
      "type": "script",
      "file": "Rules/Player/research-complete.js"
    },
    {
      "type": "script",
      "file": "Rules/City/yield.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-player-science/plugin.json
{
  "name": "base-player-science",
  "description": "A bridge for players to allow and control researching advances.",
  "dependencies": [
    "base-science",
    "core-player",
    "core-registry",
    "core-rules",
    "core-science"
  ],
  "components": [
    {
      "type": "script",
      "file": "PlayerResearchRegistry.js"
    },
    {
      "type": "script",
      "file": "PlayerResearch.js"
    },
    {
      "type": "script",
      "file": "Events/Player/yield.js"
    },
    {
      "type": "script",
      "file": "Events/Player/added.js"
    },
    {
      "type": "script",
      "file": "Events/Game/start.js"
    },
    {
      "type": "script",
      "file": "Events/City/yield.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-goody-hut-city/plugin.json
{
  "name": "base-goody-hut-city",
  "version": "0.1.0",
  "dependencies": [
    "core-goody-huts",
    "core-rules-registry",
    "core-rules",
    "base-terrain",
    "core-city"
  ],
  "components": [
    {
      "type": "script",
      "file": "Rules/GoodyHut/action.js"
    },
    {
      "type": "script",
      "file": "registerRules.js"
    },
    {
      "type": "script",
      "file": "FoundCity.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-governments/plugin.json
{
  "name": "base-governments",
  "version": "0.0.1",
  "dependencies": [
    "base-player-science",
    "base-science",
    "base-terrain-features",
    "base-terrain-yields",
    "core-government",
    "core-rules"
  ],
  "components": [
    {
      "type": "script",
      "file": "Governments/Anarchy.js"
    },
    {
      "type": "script",
      "file": "Governments/Despotism.js"
    },
    {
      "type": "script",
      "file": "Governments/Monarchy.js"
    },
    {
      "type": "script",
      "file": "Governments/Republic.js"
    },
    {
      "type": "script",
      "file": "Rules/Governments/availability.js"
    },
    {
      "type": "script",
      "file": "Governments.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-unit-actions/plugin.json
{
  "name": "base-unit-actions",
  "version": "0.1.0",
  "dependencies": [
    "base-terrain",
    "base-unit",
    "base-unit-improvements",
    "core-city",
    "core-rules",
    "core-terrain",
    "core-unit",
    "core-unit-actions",
    "base-tile-improvements",
    "core-tile-improvements"
  ],
  "components": [
    {
      "type": "script",
      "file": "Action/Attack.js"
    },
    {
      "type": "script",
      "file": "Action/CaptureCity.js"
    },
    {
      "type": "script",
      "file": "Action/BoardTransport.js"
    },
    {
      "type": "script",
      "file": "Action/BuildIrrigation.js"
    },
    {
      "type": "script",
      "file": "Action/BuildMine.js"
    },
    {
      "type": "script",
      "file": "Action/BuildRoad.js"
    },
    {
      "type": "script",
      "file": "Action/DelayedAction.js"
    },
    {
      "type": "script",
      "file": "Action/Fortify.js"
    },
    {
      "type": "script",
      "file": "Action/FoundCity.js"
    },
    {
      "type": "script",
      "file": "Action/Move.js"
    },
    {
      "type": "script",
      "file": "Action/NoOrders.js"
    },
    {
      "type": "script",
      "file": "Actions.js"
    },
    {
      "type": "script",
      "file": "register.js"
    },
    {
      "type": "script",
      "file": "Rules/Unit/action.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-goody-hut-gold/plugin.json
{
  "name": "base-goody-hut-gold",
  "version": "0.1.0",
  "dependencies": [
    "core-goody-huts",
    "core-rules-registry",
    "core-rules",
    "base-currency"
  ],
  "components": [
    {
      "type": "script",
      "file": "Rules/GoodyHut/action.js"
    },
    {
      "type": "script",
      "file": "registerRules.js"
    },
    {
      "type": "script",
      "file": "Gold.js"
    }
  ]
}
