=== dom111/civ-clone/src/Plugin/Schema.json
{
  "$id": "https://github.com/dom111/civ-clone/plugin.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "pluginName": {
      "type": "string",
      "description": "The name of the plugin. This MUST match the directory that contains the plugin.",
      "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$"
    }
  },

  "title": "Plugin",
  "properties": {
    "name": {
      "$ref": "#/definitions/pluginName"
    },
    "description": {
      "description": "An optional description of the plugin",
      "type": "string"
    },
    "version": {
      "description": "A version definition in MAJOR.MINOR.PATCH.",
      "type": "string",
      "pattern": "^[0-9]+.[0-9]+.[0-9]+(-[A-Za-z0-9]+)*$"
    },
    "components": {
      "description": "A list of the plugin's components.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "description": "The type of component.",
            "enum": [
              "script"
            ]
          },
          "file": {
            "description": "The relative path to the component.",
            "type": "string",
            "pattern": "([A-Za-z0-9]+/)*[A-Za-z0-9]+(.[A-Za-z0-9]+)"
          }
        }
      }
    },
    "dependencies": {
      "description": "The other plugins that this plugin is dependent on.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/pluginName"
      }
    },
    "required": {
      "name": true,
      "version": true
    }
  },
  "type": "object"
}

=== dom111/civ-clone/plugins/enabled/base-city-improvement-library/plugin.json
{
  "name": "base-city-improvement-library",
  "version": "0.1.0",
  "dependencies": [
    "base-city",
    "base-city-improvements",
    "base-currency",
    "core-city-improvement",
    "core-rules"
  ],
  "components": [
    {
      "type": "script",
      "file": "registerAvailableCityBuildItem.js"
    },
    {
      "type": "script",
      "file": "Library.js"
    },
    {
      "type": "script",
      "file": "Rules/City/build-cost.js"
    },
    {
      "type": "script",
      "file": "Rules/City/cost.js"
    },
    {
      "type": "script",
      "file": "registerRules.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-wonder-great-wall/plugin.json
{
  "name": "base-wonder-great-wall",
  "version": "0.1.0",
  "dependencies": [
    "base-city",
    "base-wonders",
    "core-rules-registry",
    "core-wonder"
  ],
  "components": [
    {
      "type": "script",
      "file": "registerWonder.js"
    },
    {
      "type": "script",
      "file": "GreatWall.js"
    },
    {
      "type": "script",
      "file": "Rules/City/build-cost.js"
    },
    {
      "type": "script",
      "file": "registerRules.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-city-improvement-citywalls/plugin.json
{
  "name": "base-city-improvement-citywalls",
  "version": "0.1.0",
  "dependencies": [
    "base-city",
    "base-city-improvements",
    "base-currency",
    "core-city-improvement",
    "core-rules-registry"
  ],
  "components": [
    {
      "type": "script",
      "file": "registerAvailableCityBuildItem.js"
    },
    {
      "type": "script",
      "file": "Rules/City/build-cost.js"
    },
    {
      "type": "script",
      "file": "Rules/City/cost.js"
    },
    {
      "type": "script",
      "file": "registerRules.js"
    },
    {
      "type": "script",
      "file": "CityWalls.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/game-report/plugin.json
{
  "name": "game-report",
  "version": "0.1.0",
  "dependencies": [
    "core-city",
    "core-turn-based-game",
    "core-unit",
    "core-city-improvement",
    "base-player-government",
    "base-currency",
    "core-tile-improvements",
    "base-science",
    "base-unit-improvements",
    "core-player"
  ],
  "components": [
    {
      "type": "script",
      "file": "Events/Turn/end.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-wonders/plugin.json
{
  "name": "base-wonders",
  "version": "0.1.0",
  "dependencies": [
    "core-rules",
    "core-wonder",
    "base-city",
    "core-rules-registry"
  ],
  "components": [
    {
      "type": "script",
      "file": "Rules/City/build-cost.js"
    },
    {
      "type": "script",
      "file": "Rules/City/build.js"
    },
    {
      "type": "script",
      "file": "Rules/City/building-complete.js"
    },
    {
      "type": "script",
      "file": "registerRules.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-city-improvement-colosseum/plugin.json
{
  "name": "base-city-improvement-colosseum",
  "version": "0.1.0",
  "dependencies": [
    "base-city",
    "base-city-happiness",
    "base-city-improvements",
    "base-currency",
    "core-city-improvement",
    "core-rules-registry"
  ],
  "components": [
    {
      "type": "script",
      "file": "registerAvailableCityBuildItem.js"
    },
    {
      "type": "script",
      "file": "Colosseum.js"
    },
    {
      "type": "script",
      "file": "Rules/City/build-cost.js"
    },
    {
      "type": "script",
      "file": "Rules/City/cost.js"
    },
    {
      "type": "script",
      "file": "registerRules.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-city-improvement-granary/plugin.json
{
  "name": "base-city-improvement-granary",
  "version": "0.1.0",
  "dependencies": [
    "base-city",
    "base-city-improvements",
    "base-currency",
    "base-terrain-yields",
    "core-city-improvement",
    "core-rules"
  ],
  "components": [
    {
      "type": "script",
      "file": "registerAvailableCityBuildItem.js"
    },
    {
      "type": "script",
      "file": "Granary.js"
    },
    {
      "type": "script",
      "file": "Rules/City/build-cost.js"
    },
    {
      "type": "script",
      "file": "Rules/City/grow.js"
    },
    {
      "type": "script",
      "file": "Rules/City/cost.js"
    },
    {
      "type": "script",
      "file": "registerRules.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-wonders-civ1/plugin.json
{
  "name": "base-wonders-civ1",
  "version": "0.1.0",
  "dependencies": [
    "base-wonder-colossus",
    "base-wonder-copernicus-observatory",
    "base-wonder-great-library",
    "base-wonder-great-wall",
    "base-wonder-hanging-gardens",
    "base-wonder-lighthouse",
    "base-wonder-magellans-expedition",
    "base-wonder-oracle",
    "base-wonder-pyramids"
  ],
  "components": [
    {
      "type": "script",
      "file": "Wonders.js"
    }
  ]
}
