=== dom111/civ-clone/src/Plugin/Schema.json
{
  "$id": "https://github.com/dom111/civ-clone/plugin.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "pluginName": {
      "type": "string",
      "description": "The name of the plugin. This MUST match the directory that contains the plugin.",
      "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$"
    }
  },

  "title": "Plugin",
  "properties": {
    "name": {
      "$ref": "#/definitions/pluginName"
    },
    "description": {
      "description": "An optional description of the plugin",
      "type": "string"
    },
    "version": {
      "description": "A version definition in MAJOR.MINOR.PATCH.",
      "type": "string",
      "pattern": "^[0-9]+.[0-9]+.[0-9]+(-[A-Za-z0-9]+)*$"
    },
    "components": {
      "description": "A list of the plugin's components.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "description": "The type of component.",
            "enum": [
              "script"
            ]
          },
          "file": {
            "description": "The relative path to the component.",
            "type": "string",
            "pattern": "([A-Za-z0-9]+/)*[A-Za-z0-9]+(.[A-Za-z0-9]+)"
          }
        }
      }
    },
    "dependencies": {
      "description": "The other plugins that this plugin is dependent on.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/pluginName"
      }
    },
    "required": {
      "name": true,
      "version": true
    }
  },
  "type": "object"
}

=== dom111/civ-clone/plugins/enabled/base-yield-trade/plugin.json
{
  "name": "base-yield-trade",
  "description": "To add 'trade' yields to the tiles as per the original Civilization.",
  "version": "0.0.1",
  "dependencies": [
    "base-terrain",
    "base-terrain-improvements",
    "core-rules",
    "core-yields"
  ],
  "components": [
    {
      "type": "script",
      "file": "Yields/Trade.js"
    },
    {
      "type": "script",
      "file": "Rules/Yields/Desert.js"
    },
    {
      "type": "script",
      "file": "Rules/Yields/Grassland.js"
    },
    {
      "type": "script",
      "file": "Rules/Yields/Ocean.js"
    },
    {
      "type": "script",
      "file": "Rules/Yields/Plains.js"
    },
    {
      "type": "script",
      "file": "Rules/Yields/River.js"
    },
    {
      "type": "script",
      "file": "register.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-city-improvement-palace/plugin.json
{
  "name": "base-city-improvement-palace",
  "version": "0.1.0",
  "dependencies": [
    "base-city",
    "base-city-improvements",
    "core-city",
    "core-city-improvement",
    "core-rules"
  ],
  "components": [
    {
      "type": "script",
      "file": "registerAvailableCityBuildItem.js"
    },
    {
      "type": "script",
      "file": "Rules/City/build-cost.js"
    },
    {
      "type": "script",
      "file": "Rules/City/created.js"
    },
    {
      "type": "script",
      "file": "registerRules.js"
    },
    {
      "type": "script",
      "file": "Palace.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-units-civ1/plugin.json
{
  "name": "base-units-civ1",
  "version": "0.1.0",
  "dependencies": [
    "base-unit-catapult",
    "base-unit-chariot",
    "base-unit-horseman",
    "base-unit-knight",
    "base-unit-musketman",
    "base-unit-settlers",
    "base-unit-warrior",
    "base-unit-spearman",
    "base-unit-swordman"
  ],
  "components": [
    {
      "type": "script",
      "file": "Units.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-wonder-colossus/plugin.json
{
  "name": "base-wonder-colossus",
  "version": "0.1.0",
  "dependencies": [
    "base-city",
    "base-science",
    "base-terrain-yield-trade",
    "base-wonders",
    "core-rules",
    "core-rules-registry",
    "core-wonder"
  ],
  "components": [
    {
      "type": "script",
      "file": "registerWonder.js"
    },
    {
      "type": "script",
      "file": "Rules/City/build-cost.js"
    },
    {
      "type": "script",
      "file": "Rules/City/yield.js"
    },
    {
      "type": "script",
      "file": "registerRules.js"
    },
    {
      "type": "script",
      "file": "Colossus.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-goody-huts/plugin.json
{
  "name": "base-goody-huts",
  "version": "0.1.0",
  "dependencies": [
    "core-goody-huts",
    "core-rules-registry",
    "core-rules"
  ],
  "components": [
    {
      "type": "script",
      "file": "Rules/World/built.js"
    },
    {
      "type": "script",
      "file": "Rules/Tile/goody-hut.js"
    },
    {
      "type": "script",
      "file": "Rules/Unit/moved.js"
    },
    {
      "type": "script",
      "file": "Rules/GoodyHut/discovered.js"
    },
    {
      "type": "script",
      "file": "registerRules.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-terrain-distribution/plugin.json
{
  "name": "base-terrain-distribution",
  "version": "0.1.0",
  "dependencies": [
    "base-terrain",
    "core-rules",
    "core-terrain"
  ],
  "components": [
    {
      "type": "script",
      "file": "Rules/Forest.js"
    },
    {
      "type": "script",
      "file": "Rules/Arctic.js"
    },
    {
      "type": "script",
      "file": "Rules/Desert.js"
    },
    {
      "type": "script",
      "file": "Rules/Grassland.js"
    },
    {
      "type": "script",
      "file": "Rules/Hills.js"
    },
    {
      "type": "script",
      "file": "Rules/Jungle.js"
    },
    {
      "type": "script",
      "file": "Rules/Mountains.js"
    },
    {
      "type": "script",
      "file": "Rules/Ocean.js"
    },
    {
      "type": "script",
      "file": "Rules/Plains.js"
    },
    {
      "type": "script",
      "file": "Rules/River.js"
    },
    {
      "type": "script",
      "file": "Rules/Swamp.js"
    },
    {
      "type": "script",
      "file": "Rules/Tundra.js"
    },
    {
      "type": "script",
      "file": "Rules/groups.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-wonder-hanging-gardens/plugin.json
{
  "name": "base-wonder-hanging-gardens",
  "version": "0.1.0",
  "dependencies": [
    "base-city",
    "base-city-happiness",
    "base-science",
    "base-wonders",
    "core-rules",
    "core-rules-registry",
    "core-wonder"
  ],
  "components": [
    {
      "type": "script",
      "file": "registerWonder.js"
    },
    {
      "type": "script",
      "file": "HangingGardens.js"
    },
    {
      "type": "script",
      "file": "Rules/City/build-cost.js"
    },
    {
      "type": "script",
      "file": "Rules/City/yield.js"
    },
    {
      "type": "script",
      "file": "registerRules.js"
    }
  ]
}

=== dom111/civ-clone/plugins/enabled/base-unit-improvements/plugin.json
{
  "name": "base-unit-improvements",
  "version": "0.0.1",
  "dependencies": [
    "core-unit"
  ],
  "components": [
    {
      "type": "script",
      "file": "Improvement.js"
    },
    {
      "type": "script",
      "file": "Improvements.js"
    },
    {
      "type": "script",
      "file": "Improvements/Fortified.js"
    },
    {
      "type": "script",
      "file": "Improvements/Veteran.js"
    }
  ]
}
